CREATE TABLE "love_results" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"person_a_name" varchar(100) NOT NULL,
	"person_a_date_of_birth" varchar(20) NOT NULL,
	"person_a_favorite_number" integer NOT NULL,
	"person_a_favorite_color" varchar(50),
	"person_a_zodiac_sign" varchar(50),
	"person_a_hobby" varchar(100),
	"person_a_personality" text,
	"person_b_name" varchar(100) NOT NULL,
	"person_b_date_of_birth" varchar(20) NOT NULL,
	"person_b_favorite_number" integer NOT NULL,
	"person_b_favorite_color" varchar(50),
	"person_b_zodiac_sign" varchar(50),
	"person_b_hobby" varchar(100),
	"person_b_personality" text,
	"relationship_type" varchar(50) NOT NULL,
	"extra_context" text,
	"score" integer NOT NULL,
	"status" varchar(50) NOT NULL,
	"summary" text NOT NULL,
	"name_compatibility" text,
	"birth_compatibility" text,
	"number_vibe" text,
	"color_vibe" text,
	"zodiac_vibe" text,
	"strengths" jsonb NOT NULL,
	"warnings" jsonb NOT NULL,
	"funny_line" text,
	"disclaimer" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
